CXX = g++
CXXFLAGS = -std=c++11 -Wall -Wextra -g
TARGET = library_system
SOURCES = main.cpp publication.cpp book.cpp magazine.cpp member.cpp library.cpp
OBJECTS = $(SOURCES:.cpp=.o)
HEADERS = publication.h book.h magazine.h journal.h member.h library.h

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJECTS)

%.o: %.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(TARGET)

run: $(TARGET)
	./$(TARGET)

test: $(TARGET)
	./$(TARGET) test

.PHONY: all clean run test
